FROM kindest/node:v1.18.2@sha256:7b27a6d0f2517ff88ba444025beae41491b016bc6af573ba467b70c5e8e0d85f

RUN clean-install aufs-tools \
	&& sed -i 's/\(\[plugins."io.containerd.grpc.v1.cri".containerd\]\)/\1\n  snapshotter = "aufs"/' \
		/etc/containerd/config.toml \
	&& mkdir /var/lib/containerd/io.containerd.snapshotter.v1.aufs
